sudo: false

language: node_js

node_js:
  - "0.10.41"


before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"
  - export PATH="$HOME/.meteor:$PATH"

script: "spacejam test-packages ./"
